#!/usr/bin/env python3
"""Gate false-positive audit — the evidence ADR-0009 requires before promoting a deterministic gate from
SHADOW to BLOCK in the per-leaf loop.

The conformance and contract-pre-flight gates already run on every leaf (controller_pipeline.run_pipeline,
which controller_goal runs per leaf), but in SHADOW: they observe and stream findings, they do not block
convergence. The controller flips a gate to blocking with a single auditable line (`CONFORMANCE_GATE=block`)
only "after telemetry shows effective-FP ~0" (ADR-0009 / Tricorder shadow-first). That telemetry did not
exist — nothing measured how often a gate flags a KNOWN-GOOD artifact. This harness is that instrument.

It is part of the small TRUSTED kernel (ADR-0011): the gate that certifies the certifier is hand-built and
tested, never generated by the (unmeasured) pipeline it audits.

Method — LLM-free, cheap, re-runnable. A curated corpus of fixtures under `gate_fixtures/`, each a
(contract, artifact) pair with a declared expectation in `expect.json`:
  - a fixture that should PASS but the gate FAILS  = a FALSE POSITIVE (the number that gates promotion);
  - a fixture that should FAIL but the gate PASSES = a FALSE NEGATIVE (proves the gate still has teeth —
    an FP-free gate that catches nothing is useless, so promotion requires BOTH FP==0 and FN==0);
  - a gate that does not apply to a fixture it asserts = a MISFIRE (a fixture-authoring error, never a pass).

Promotion criterion per gate: effective-FP == 0 over the good fixtures AND every bad fixture is caught
(non-gameable) AND at least one good and one bad fixture exist. When met, the one-line flip is printed.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import conformance  # noqa: E402
import contract_preflight  # noqa: E402

DEFAULT_FIXTURES = Path(__file__).resolve().parent / "gate_fixtures"
REPO_ROOT = Path(__file__).resolve().parent.parent
GATES = ("preflight", "conformance")
_FLIP = {"conformance": "CONFORMANCE_GATE=block", "preflight": "CONTRACT_PREFLIGHT=block"}


def _gate_status(report: dict) -> str:
    """'pass' | 'fail' | 'na' for a gate report. 'na' = the gate did not apply (it cannot be a false
    positive/negative — it simply did not run), surfaced so a misauthored fixture is never scored as a pass."""
    if not isinstance(report, dict) or not report.get("applicable", False):
        return "na"
    return "pass" if report.get("passed") else "fail"


def _classify(expected: str, actual: str) -> str:
    if actual == "na":
        return "misfire"                                  # gate did not run on a fixture that asserts it
    if expected == "pass":
        return "correct_accept" if actual == "pass" else "false_positive"
    return "true_positive" if actual == "fail" else "false_negative"   # expected == "fail"


def run_fixture(fixture_dir: Path) -> dict:
    contract = json.loads((fixture_dir / "contract.json").read_text(encoding="utf-8"))
    expect = json.loads((fixture_dir / "expect.json").read_text(encoding="utf-8"))
    # A fixture may audit a REAL in-repo artifact in place: `workdir` (relative to the repo root) sets the
    # conformance cwd so the contract's entrypoint can point at a real script (e.g. scripts/merge-gate.py)
    # without copying it. Absent `workdir`, the artifact lives in the fixture dir (the synthetic fixtures).
    workdir = expect.get("workdir")
    cwd = (REPO_ROOT / workdir).resolve() if workdir else fixture_dir
    reports = {
        "preflight": contract_preflight.preflight(contract),
        "conformance": conformance.run_conformance(
            contract, conformance.subprocess_runner(timeout=20), cwd=str(cwd)),
    }
    gates = {}
    for gate in GATES:
        if gate not in expect:
            continue
        actual = _gate_status(reports[gate])
        gates[gate] = {
            "expected": expect[gate],
            "actual": actual,
            "verdict": _classify(expect[gate], actual),
            "findings": [f for f in reports[gate].get("findings", []) if not f.get("passed", True)],
        }
    return {"label": expect.get("label", fixture_dir.name), "kind": expect.get("kind"), "gates": gates}


def audit(fixtures_root: Path) -> dict:
    fixtures = sorted(p for p in fixtures_root.iterdir()
                      if p.is_dir() and (p / "contract.json").exists())
    per_fixture = [run_fixture(p) for p in fixtures]
    verdicts = ("correct_accept", "false_positive", "true_positive", "false_negative", "misfire")
    tally = {g: {v: 0 for v in verdicts} for g in GATES}
    for fx in per_fixture:
        for gate, r in fx["gates"].items():
            tally[gate][r["verdict"]] += 1
    summary = {}
    for gate, t in tally.items():
        goods = t["correct_accept"] + t["false_positive"]
        bads = t["true_positive"] + t["false_negative"]
        summary[gate] = {
            **t,
            "good_fixtures": goods,
            "bad_fixtures": bads,
            "effective_fp_rate": (t["false_positive"] / goods) if goods else None,
            "catch_rate": (t["true_positive"] / bads) if bads else None,
            "promotable": (t["false_positive"] == 0 and t["false_negative"] == 0 and t["misfire"] == 0
                           and goods >= 1 and bads >= 1),
        }
    return {"fixtures": per_fixture, "summary": summary}


_SYM = {"correct_accept": "ok ", "true_positive": "ok ", "false_positive": "FP!",
        "false_negative": "FN!", "misfire": "NA!"}


def render(report: dict) -> str:
    lines = ["gate false-positive audit", "=" * 64]
    for fx in report["fixtures"]:
        for gate, r in fx["gates"].items():
            lines.append(f"  [{_SYM[r['verdict']]}] {fx['label']:<16} {gate:<11} "
                         f"expect={r['expected']:<4} got={r['actual']:<4} {r['verdict']}")
    lines.append("-" * 64)
    any_audited = False
    for gate, s in report["summary"].items():
        if not (s["good_fixtures"] or s["bad_fixtures"]):
            continue
        any_audited = True
        fp = "n/a" if s["effective_fp_rate"] is None else f"{s['effective_fp_rate']:.0%}"
        cr = "n/a" if s["catch_rate"] is None else f"{s['catch_rate']:.0%}"
        lines.append(f"  {gate:<11} FP={fp:<4} (good={s['good_fixtures']})  "
                     f"catch={cr:<4} (bad={s['bad_fixtures']})  -> "
                     f"{'PROMOTABLE' if s['promotable'] else 'hold'}")
        if s["promotable"]:
            lines.append(f"              evidence supports the one-line flip: {_FLIP[gate]}")
    if not any_audited:
        lines.append("  (no fixtures asserted any gate)")
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Gate false-positive audit (ADR-0009 shadow->block evidence)")
    ap.add_argument("--fixtures", type=Path, default=DEFAULT_FIXTURES)
    ap.add_argument("--json", action="store_true", help="emit the machine record")
    ap.add_argument("--require-promotable", action="store_true",
                    help="exit nonzero unless every audited gate is promotable (for CI)")
    args = ap.parse_args(argv)
    report = audit(args.fixtures)
    print(json.dumps(report, indent=2, ensure_ascii=False) if args.json else render(report))
    if args.require_promotable:
        audited = [s for s in report["summary"].values() if s["good_fixtures"] or s["bad_fixtures"]]
        return 0 if audited and all(s["promotable"] for s in audited) else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
